### ISSUE TITLE
Cannot build Microdot Solution

### ISSUE THREAD

**Issue by suchym** [gigya/microdot#361]
I downloaded source code of Microdot and I tried to compile solution.
I got exception while paket tries to download Gigya.OrleansDashboard.NetStandard 3.0.8.

Here is message:

Downloading Gigya.OrleansDashboard.NetStandard 3.0.8
Source 'http://nuget.gigya.net/nugetForVS/nuget' exception: System.Exception: Could not retrieve data from 'http://nuget.gigya.net/nugetForVS/nuget/FindPackagesById()?semVerLevel=2.0.0&id='Gigya.OrleansDashboard.NetStandard'' ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The remote name could not be resolved: 'nuget.gigya.net'
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at Paket.NetUtils.resolveAuth@488-2.Invoke(Exception _arg1)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@522.Invoke(AsyncParams`1 args)
   --- End of inner exception stack trace ---
   at Paket.NetUtils.getFromUrl@540-2.Invoke(Exception _arg3)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@522.Invoke(AsyncParams`1 args)
Something went wrong while downloading Gigya.OrleansDashboard.NetStandard 3.0.8
Message: Could not download Gigya.OrleansDashboard.NetStandard 3.0.8.

I was able to work with version 3.0.5. My currently downloaded version is 3.1.6.

**Comment by Madpixel6** [comment]
Reproduced in latest version, looks like nuget.gigya.net is down/innaccessible to public network. 
Gigya.ServiceContract can be swapped with a [nuget version](https://www.nuget.org/packages/Gigya.ServiceContract), but I couldn't find a public mirror of gigya.orleansdashboard.netstandard
`Possible Performance degradation, blacklist '1_http://nuget.gigya.net/nugetForVS/nuget/Packages(Id='gigya.orleansdashboard.netstandard',Version='3.0.8')'
Possible Performance degradation, blacklist '1_http://nuget.gigya.net/nugetForVS/nuget/Packages(Id='Gigya.OrleansDashboard.NetStandard',Version='3.0.8')'
Possible Performance degradation, blacklist '2_http://nuget.gigya.net/nugetForVS/nuget/Packages?$filter=(Id eq 'Gigya.OrleansDashboard.NetStandard') and (NormalizedVersion eq '3.0.8')'
Possible Performance degradation, blacklist '2_http://nuget.gigya.net/nugetForVS/nuget/Packages?$filter=(tolower(Id) eq 'gigya.orleansdashboard.netstandard') and (NormalizedVersion eq '3.0.8')'
Possible Performance degradation, blacklist '2_http://nuget.gigya.net/nugetForVS/nuget/Packages?$filter=(Id eq 'Gigya.OrleansDashboard.NetStandard') and (Version eq '3.0.8')'
Possible Performance degradation, blacklist '2_http://nuget.gigya.net/nugetForVS/nuget/Packages?$filter=(tolower(Id) eq 'gigya.orleansdashboard.netstandard') and (Version eq '3.0.8')'
Source 'http://nuget.gigya.net/nugetForVS/nuget' exception: System.Exception: Could not retrieve data from 'http://nuget.gigya.net/nugetForVS/nuget/FindPackagesById()?semVerLevel=2.0.0&id='Gigya.OrleansDashboard.NetStandard'' ---> System.Ne`
